# Generated by Django 5.2.8 on 2025-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pan',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pastel_establecido',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postre',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tarta',
            name='descripcion',
            field=models.CharField(blank=True, default='Sin descripción', max_length=255, null=True),
        ),
    ]
