# Generated by Django 5.2.8 on 2025-11-24 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasteleria', '0002_alter_pan_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(related_name='pedidos', through='pasteleria.DETALLE', to='pasteleria.producto'),
        ),
        migrations.AlterField(
            model_name='pastel_establecido',
            name='idEstablecido',
            field=models.OneToOneField(limit_choices_to={'tipoPastel': 'ESTABLECIDO'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.pastel'),
        ),
        migrations.AlterField(
            model_name='pastel_personalizado',
            name='idPersonalizado',
            field=models.OneToOneField(limit_choices_to={'tipoPastel': 'PERSONALIZADO'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pasteleria.pastel'),
        ),
    ]
